config/routes.rb
Rails.application.routes.draw do
  resources :subtipos
  resources :tipos
  resources :categs
  resources :parrs
  resources :cants
  resources :provs
  resources :atractivos do
    collection do
      get 'add_cantones', to: 'atractivos#add_cantones'
      get 'add_parroquias', to: 'atractivos#add_parroquias'
      get 'add_tipos', to: 'atractivos#add_tipos'
      get 'add_subtipos', to: 'atractivos#add_subtipos'
      get 'add_climate_data', to: 'atractivos#add_climate_data'
    end
  end
  resources :cuestionarios do
    collection do
      get 'nextstep', to: 'cuestionarios#nextstep'
      post 'savestep', to: 'cuestionarios#savestep'
    end
  end

  root 'atractivos#index'

  match 'atract/popup/:id' => 'atractivos#popup', :via => :get
  match 'atractivos/atract/popup/:id' => 'atractivos#popup', :via => :get
  match '/?idCanton=:id' => 'atractivos#index', :via => :get
  match 'atractivos/?idCanton=:id' => 'atractivos#index', :via => :get

end

app/models/categ.rb
class Categ < ActiveRecord::Base
  has_many :tipo
  has_many :subtipo, through: :tipo
  has_one :atractivo

  def to_s
    name
  end
end

app/controllers/categs_controller.rb
class CategsController < ApplicationController
  before_action :set_categ, only: [:show, :edit, :update, :destroy]

  # GET /categs
  # GET /categs.json
  def index
    @categs = Categ.all
  end

  # GET /categs/1
  # GET /categs/1.json
  def show
  end

  # GET /categs/new
  def new
    @categ = Categ.new
  end

  # GET /categs/1/edit
  def edit
  end

  # POST /categs
  # POST /categs.json
  def create
    @categ = Categ.new(categ_params)

    respond_to do |format|
      if @categ.save
        format.html { redirect_to @categ, notice: 'Categ was successfully created.' }
        format.json { render :show, status: :created, location: @categ }
      else
        format.html { render :new }
        format.json { render json: @categ.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categs/1
  # PATCH/PUT /categs/1.json
  def update
    respond_to do |format|
      if @categ.update(categ_params)
        format.html { redirect_to @categ, notice: 'Categ was successfully updated.' }
        format.json { render :show, status: :ok, location: @categ }
      else
        format.html { render :edit }
        format.json { render json: @categ.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categs/1
  # DELETE /categs/1.json
  def destroy
    @categ.destroy
    respond_to do |format|
      format.html { redirect_to categs_url, notice: 'Categ was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_categ
      @categ = Categ.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def categ_params
      params.require(:categ).permit(:name)
    end
end

app/helpers/categs_helper.rb
module CategsHelper
end

app/views/categs/_form.html.erb
<%= form_for(@categ) do |f| %>
  <% if @categ.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@categ.errors.count, "error") %> prohibited this categ from being saved:</h2>

      <ul>
      <% @categ.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categs/edit.html.erb
<h1>Editing Categ</h1>

<%= render 'form' %>

<%= link_to 'Show', @categ %> |
<%= link_to 'Back', categs_path %>

app/views/categs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categs.each do |categ| %>
      <tr>
        <td><%= categ.name %></td>
        <td><%= link_to 'Show', categ %></td>
        <td><%= link_to 'Edit', edit_categ_path(categ) %></td>
        <td><%= link_to 'Destroy', categ, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Categ', new_categ_path %>

app/views/categs/new.html.erb
<h1>New Categ</h1>

<%= render 'form' %>

<%= link_to 'Back', categs_path %>

app/views/categs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @categ.name %>
</p>

<%= link_to 'Edit', edit_categ_path(@categ) %> |
<%= link_to 'Back', categs_path %>