config/routes.rb
Rails.application.routes.draw do
  resources :subtipos
  resources :tipos
  resources :categs
  resources :parrs
  resources :cants
  resources :provs
  resources :atractivos do
    collection do
      get 'add_cantones', to: 'atractivos#add_cantones'
      get 'add_parroquias', to: 'atractivos#add_parroquias'
      get 'add_tipos', to: 'atractivos#add_tipos'
      get 'add_subtipos', to: 'atractivos#add_subtipos'
      get 'add_climate_data', to: 'atractivos#add_climate_data'
    end
  end
  resources :cuestionarios do
    collection do
      get 'nextstep', to: 'cuestionarios#nextstep'
      post 'savestep', to: 'cuestionarios#savestep'
    end
  end

  root 'atractivos#index'

  match 'atract/popup/:id' => 'atractivos#popup', :via => :get
  match 'atractivos/atract/popup/:id' => 'atractivos#popup', :via => :get
  match '/?idCanton=:id' => 'atractivos#index', :via => :get
  match 'atractivos/?idCanton=:id' => 'atractivos#index', :via => :get

end

app/models/cant.rb
class Cant < ActiveRecord::Base
  belongs_to :prov
  has_many :parrs
  has_one :atractivo

  def to_s
    name
  end
end

app/controllers/cants_controller.rb
class CantsController < ApplicationController
  before_action :set_cant, only: [:show, :edit, :update, :destroy]

  # GET /cants
  # GET /cants.json
  def index
    @cants = Cant.all
  end

  # GET /cants/1
  # GET /cants/1.json
  def show
  end

  # GET /cants/new
  def new
    @cant = Cant.new
  end

  # GET /cants/1/edit
  def edit
  end

  # POST /cants
  # POST /cants.json
  def create
    @cant = Cant.new(cant_params)

    respond_to do |format|
      if @cant.save
        format.html { redirect_to @cant, notice: 'Cant was successfully created.' }
        format.json { render :show, status: :created, location: @cant }
      else
        format.html { render :new }
        format.json { render json: @cant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cants/1
  # PATCH/PUT /cants/1.json
  def update
    respond_to do |format|
      if @cant.update(cant_params)
        format.html { redirect_to @cant, notice: 'Cant was successfully updated.' }
        format.json { render :show, status: :ok, location: @cant }
      else
        format.html { render :edit }
        format.json { render json: @cant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cants/1
  # DELETE /cants/1.json
  def destroy
    @cant.destroy
    respond_to do |format|
      format.html { redirect_to cants_url, notice: 'Cant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cant
      @cant = Cant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cant_params
      params.require(:cant).permit(:name, :prov_id)
    end
end

app/helpers/cants_helper.rb
module CantsHelper
end

app/views/cants/_cant.html.erb
<option value="<%= cant.id %>"><%= cant.name.titleize %></option>

app/views/cants/_form.html.erb
<%= form_for(@cant) do |f| %>
  <% if @cant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cant.errors.count, "error") %> prohibited this cant from being saved:</h2>

      <ul>
      <% @cant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :prov_id %><br>
    <%= f.collection_select(:prov_id, Prov.all, :id, :name) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cants/edit.html.erb
<h1>Editing Cant</h1>

<%= render 'form' %>

<%= link_to 'Show', @cant %> |
<%= link_to 'Back', cants_path %>

app/views/cants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Prov</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cants.each do |cant| %>
      <tr>
        <td><%= cant.name %></td>
        <td><%= cant.prov %></td>
        <td><%= link_to 'Show', cant %></td>
        <td><%= link_to 'Edit', edit_cant_path(cant) %></td>
        <td><%= link_to 'Destroy', cant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cant', new_cant_path %>

app/views/cants/new.html.erb
<h1>New Cant</h1>

<%= render 'form' %>

<%= link_to 'Back', cants_path %>

app/views/cants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cant.name %>
</p>

<p>
  <strong>Prov:</strong>
  <%= @cant.prov %>
</p>

<%= link_to 'Edit', edit_cant_path(@cant) %> |
<%= link_to 'Back', cants_path %>