config/routes.rb
Rails.application.routes.draw do
  resources :subtipos
  resources :tipos
  resources :categs
  resources :parrs
  resources :cants
  resources :provs
  resources :atractivos do
    collection do
      get 'add_cantones', to: 'atractivos#add_cantones'
      get 'add_parroquias', to: 'atractivos#add_parroquias'
      get 'add_tipos', to: 'atractivos#add_tipos'
      get 'add_subtipos', to: 'atractivos#add_subtipos'
      get 'add_climate_data', to: 'atractivos#add_climate_data'
    end
  end
  resources :cuestionarios do
    collection do
      get 'nextstep', to: 'cuestionarios#nextstep'
      post 'savestep', to: 'cuestionarios#savestep'
    end
  end

  root 'atractivos#index'

  match 'atract/popup/:id' => 'atractivos#popup', :via => :get
  match 'atractivos/atract/popup/:id' => 'atractivos#popup', :via => :get
  match '/?idCanton=:id' => 'atractivos#index', :via => :get
  match 'atractivos/?idCanton=:id' => 'atractivos#index', :via => :get

end

app/models/tipo.rb
class Tipo < ActiveRecord::Base
  belongs_to :categ
  has_many :subtipo
  has_one :atractivo

  def to_s
    name
  end
end

app/controllers/tipos_controller.rb
class TiposController < ApplicationController
  before_action :set_tipo, only: [:show, :edit, :update, :destroy]

  # GET /tipos
  # GET /tipos.json
  def index
    @tipos = Tipo.all
  end

  # GET /tipos/1
  # GET /tipos/1.json
  def show
  end

  # GET /tipos/new
  def new
    @tipo = Tipo.new
  end

  # GET /tipos/1/edit
  def edit
  end

  # POST /tipos
  # POST /tipos.json
  def create
    @tipo = Tipo.new(tipo_params)

    respond_to do |format|
      if @tipo.save
        format.html { redirect_to @tipo, notice: 'Tipo was successfully created.' }
        format.json { render :show, status: :created, location: @tipo }
      else
        format.html { render :new }
        format.json { render json: @tipo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipos/1
  # PATCH/PUT /tipos/1.json
  def update
    respond_to do |format|
      if @tipo.update(tipo_params)
        format.html { redirect_to @tipo, notice: 'Tipo was successfully updated.' }
        format.json { render :show, status: :ok, location: @tipo }
      else
        format.html { render :edit }
        format.json { render json: @tipo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipos/1
  # DELETE /tipos/1.json
  def destroy
    @tipo.destroy
    respond_to do |format|
      format.html { redirect_to tipos_url, notice: 'Tipo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipo
      @tipo = Tipo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tipo_params
      params.require(:tipo).permit(:name, :categ_id)
    end
end

app/helpers/tipos_helper.rb
module TiposHelper
end

app/views/tipos/_form.html.erb
<%= form_for(@tipo) do |f| %>
  <% if @tipo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tipo.errors.count, "error") %> prohibited this tipo from being saved:</h2>

      <ul>
      <% @tipo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :categ_id %><br>
    <%= f.collection_select(:categ_id, Categ.all, :id, :name)%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tipos/_tipo.html.erb
<option value="<%= tipo.id %>"><%= tipo.name.titleize %></option>

app/views/tipos/edit.html.erb
<h1>Editing Tipo</h1>

<%= render 'form' %>

<%= link_to 'Show', @tipo %> |
<%= link_to 'Back', tipos_path %>

app/views/tipos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tipos</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Categ</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tipos.each do |tipo| %>
      <tr>
        <td><%= tipo.name %></td>
        <td><%= tipo.categ %></td>
        <td><%= link_to 'Show', tipo %></td>
        <td><%= link_to 'Edit', edit_tipo_path(tipo) %></td>
        <td><%= link_to 'Destroy', tipo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tipo', new_tipo_path %>

app/views/tipos/new.html.erb
<h1>New Tipo</h1>

<%= render 'form' %>

<%= link_to 'Back', tipos_path %>

app/views/tipos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tipo.name %>
</p>

<p>
  <strong>Categ:</strong>
  <%= @tipo.categ %>
</p>

<%= link_to 'Edit', edit_tipo_path(@tipo) %> |
<%= link_to 'Back', tipos_path %>