config/routes.rb
Rails.application.routes.draw do
  resources :subtipos
  resources :tipos
  resources :categs
  resources :parrs
  resources :cants
  resources :provs
  resources :atractivos do
    collection do
      get 'add_cantones', to: 'atractivos#add_cantones'
      get 'add_parroquias', to: 'atractivos#add_parroquias'
      get 'add_tipos', to: 'atractivos#add_tipos'
      get 'add_subtipos', to: 'atractivos#add_subtipos'
      get 'add_climate_data', to: 'atractivos#add_climate_data'
    end
  end
  resources :cuestionarios do
    collection do
      get 'nextstep', to: 'cuestionarios#nextstep'
      post 'savestep', to: 'cuestionarios#savestep'
    end
  end

  root 'atractivos#index'

  match 'atract/popup/:id' => 'atractivos#popup', :via => :get
  match 'atractivos/atract/popup/:id' => 'atractivos#popup', :via => :get
  match '/?idCanton=:id' => 'atractivos#index', :via => :get
  match 'atractivos/?idCanton=:id' => 'atractivos#index', :via => :get

end

app/models/prov.rb
class Prov < ActiveRecord::Base
  has_many :cants
  has_one :atractivo

  def to_s
    name
  end
end

app/controllers/provs_controller.rb
class ProvsController < ApplicationController
  before_action :set_prov, only: [:show, :edit, :update, :destroy]

  # GET /provs
  # GET /provs.json
  def index
    @provs = Prov.all
  end

  # GET /provs/1
  # GET /provs/1.json
  def show
  end

  # GET /provs/new
  def new
    @prov = Prov.new
  end

  # GET /provs/1/edit
  def edit
  end

  # POST /provs
  # POST /provs.json
  def create
    @prov = Prov.new(prov_params)

    respond_to do |format|
      if @prov.save
        format.html { redirect_to @prov, notice: 'Prov was successfully created.' }
        format.json { render :show, status: :created, location: @prov }
      else
        format.html { render :new }
        format.json { render json: @prov.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /provs/1
  # PATCH/PUT /provs/1.json
  def update
    respond_to do |format|
      if @prov.update(prov_params)
        format.html { redirect_to @prov, notice: 'Prov was successfully updated.' }
        format.json { render :show, status: :ok, location: @prov }
      else
        format.html { render :edit }
        format.json { render json: @prov.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /provs/1
  # DELETE /provs/1.json
  def destroy
    @prov.destroy
    respond_to do |format|
      format.html { redirect_to provs_url, notice: 'Prov was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prov
      @prov = Prov.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prov_params
      params.require(:prov).permit(:name)
    end
end

app/helpers/provs_helper.rb
module ProvsHelper
end

app/views/provs/_form.html.erb
<%= form_for(@prov) do |f| %>
  <% if @prov.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@prov.errors.count, "error") %> prohibited this prov from being saved:</h2>

      <ul>
      <% @prov.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/provs/_prov.html.erb
<%= collection_select(:atractivo, :cant_id, @prov.cants, :id, :name, options = {:prompt => "-Select Canton-"}) %>

app/views/provs/edit.html.erb
<h1>Editing Prov</h1>

<%= render 'form' %>

<%= link_to 'Show', @prov %> |
<%= link_to 'Back', provs_path %>

app/views/provs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Provs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @provs.each do |prov| %>
      <tr>
        <td><%= prov.name %></td>
        <td><%= link_to 'Show', prov %></td>
        <td><%= link_to 'Edit', edit_prov_path(prov) %></td>
        <td><%= link_to 'Destroy', prov, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Prov', new_prov_path %>

app/views/provs/new.html.erb
<h1>New Prov</h1>

<%= render 'form' %>

<%= link_to 'Back', provs_path %>

app/views/provs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @prov.name %>
</p>

<%= link_to 'Edit', edit_prov_path(@prov) %> |
<%= link_to 'Back', provs_path %>